apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-api-service
  name: gateway-api-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: gateway-api-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api-deployment
  labels:
    app: gateway-api-deployment
spec:
  selector:
    matchLabels:
      app: gateway-api-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway-api-pod
    spec:
      containers:
      - name: gateway-api-container
        image: docker.io/learningorchestra/gatewayapi:kubernetes
        ports:
        - containerPort: 8080
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]